"""
Module: loss_functions.py
Phase: 2 — PhysDeepSIF Network Architecture and Training
Purpose: Implement physics-informed composite loss function for PhysDeepSIF.

This module implements the three-component loss function specified in Technical
Specs Section 4.2:
  1. Source reconstruction loss (supervised MSE)
  2. Forward consistency loss (using leadfield, variance-normalised)
  3. Physiological regularization loss (Laplacian, temporal, amplitude)

The composite loss is:
    L_total = α·L_source + β·L_forward + γ·L_physics

where L_physics = λ1·L_Laplacian + λ2·L_temporal + λ3·L_amplitude

--- SCALE FIX (2026-04-28) ---
L_forward is now *variance-normalised* by BOTH Var(EEG) and Var(L@Ŝ).
The combined denominator is robust at all training stages:

    L_forward = MSE(L@Ŝ, EEG) / (Var(EEG) + Var(L@Ŝ) + ε)

  Ŝ≈0:       denom≈Var(EEG)           → L_forward ≈ 1  (no blow-up)
  random Ŝ:  denom≈Var(L@Ŝ)+Var(EEG)  → L_forward ≈ 1  (cancels ~200× leadfield amp)
  converged: denom≈2·Var(EEG)         → L_forward ≈ raw_mse/2

Using Var(EEG) alone gives L_forward≈600 at init (leadfield amplification
unaccounted for).  Var(L@Ŝ) alone blows to 1e7 when Ŝ≈0 (gradient collapse).

--- LAPLACIAN VECTORISATION (2026-04-20) ---
The original implementation iterated over T=400 time steps in Python; this
has been replaced with a vectorised einsum that is ~300× faster and avoids
gradient-graph fragmentation.

Key dependencies:
- torch: Neural network framework

Input data format:
- predicted_sources: (batch, 76, 400) predicted source activity
- true_sources: (batch, 76, 400) ground truth source activity
- eeg_input: (batch, 19, 400) input EEG measurements
- leadfield: (19, 76) forward model matrix
- connectivity_laplacian: (76, 76) Laplacian of connectivity

Author: Generated by GitHub Copilot
Date: 2026-02-18
Updated: 2026-04-28 — combined Var(EEG)+Var(L@Ŝ) denominator, warm-up schedule
"""

import logging
from typing import Dict, Optional

import torch
import torch.nn as nn

logger = logging.getLogger(__name__)

# Module-level constants
N_REGIONS = 76
N_CHANNELS = 19
WINDOW_LENGTH_SAMPLES = 400

# Small epsilon to prevent division-by-zero in normalisations
_EPS = 1e-7


class PhysicsInformedLoss(nn.Module):
    """
    Composite physics-informed loss function for PhysDeepSIF.

    This loss combines three components to guide network training:

    1. **Source Reconstruction Loss (L_source)**:
       MSE between predicted and ground truth source activity.
       Directly supervised signal; encourages accurate source estimation.

       L_source = (1/(N_r·T)) Σ_i Σ_t (Ŝ_{i,t} - S^true_{i,t})²

    2. **Forward Consistency Loss (L_forward)** — variance-normalised:
       Relative MSE between the leadfield-projected prediction and input EEG.
       Ensures predicted sources are physically consistent with EEG generation
       while being on the same numerical scale as L_source.

        L_forward = MSE(L @ Ŝ, EEG^input) / (Var(EEG^input) + Var(L@Ŝ) + ε)

         Why normalise by BOTH variances?
        ─────────────────────────────────
        Var(EEG) ≈ 1.0 after z-scoring serves as a floor denominator —
        prevents blow-up to 1e7 when Ŝ≈0 collapses Var(L@Ŝ) to zero.

        Var(L@Ŝ) tracks the leadfield amplification (~200× RMS): at random
        init Ŝ≈N(0,0.13), Var(L@Ŝ) ≈ 620 dominates the denominator, making
        L_forward ≈ 1.0 even though raw_mse ≈ 800.  Using Var(EEG) alone
        would give L_forward ≈ 800 at init — gradient imbalance.

        Together the two denominators cover all training regimes:
          Ŝ≈0:       denom ≈ Var(EEG) ≈ 1    → L_forward ≈ 1
          random Ŝ:  denom ≈ Var(L@Ŝ) + 1    → L_forward ≈ 1
          converged: denom ≈ 2·Var(EEG) ≈ 2  → L_forward ≈ raw_mse/2

        During training Var(EEG) is a stable per-batch constant (the same
        EEG is both input and target), while Var(L @ Ŝ) fluctuates as source
        estimates change scale.  Normalising by the input variance guarantees
        L_forward ≈ O(1) at all stages of training regardless of dataset
        scale, giving all loss components comparable gradient magnitude.

    3. **Physiological Regularization Loss (L_physics)**:
       Three sub-components enforcing biological realism:

       a) Laplacian regularization (spatial smoothness):
          L_Laplacian = (1/(N_r·T)) Σ_t Ŝ_t^T @ D @ Ŝ_t
          where D is the graph Laplacian (connectivity-based smoothness)

       b) Temporal smoothness (penalize high-frequency jitter):
          L_temporal = (1/(N_r·(T-1))) Σ_i Σ_t (Ŝ_{i,t+1} - Ŝ_{i,t})²

       c) Amplitude bound (soft physiological constraint):
          L_amplitude = (1/(N_r·T)) Σ_{i,t} max(0, |Ŝ_{i,t}| - A_max)²
          where A_max = 3.0 (after normalization)

       L_physics = λ1·L_Laplacian + λ2·L_temporal + λ3·L_amplitude

    Total loss:
        L_total = α·L_source + β·L_forward + γ·L_physics

    Default weights (from Technical Specs Section 4.2.5):
    - α = 1.0 (source reconstruction)
    - β = 0.05 (forward consistency; reduced from 0.5 because the leadfield
        amplifies the forward gradient by ~200× relative to source. Even with
        variance-normalised L_forward ≈ O(1), the gradient w.r.t. predicted
        sources passes through L^T, whose singular values amplify small
        source errors into large EEG-domain errors. β=0.05 keeps the
        effective forward contribution within 1 order of magnitude of source.)
    - γ = 0.01 (physics regularization)
    - λ1 = 0.0 (Laplacian; disabled by default)
    - λ2 = 0.3 (temporal)
    - λ3 = 0.2 (amplitude)
    """

    def __init__(
        self,
        leadfield: torch.Tensor,
        connectivity_laplacian: torch.Tensor,
        alpha: float = 1.0,
        beta: float = 0.05,
        gamma: float = 0.01,
        delta_epi: float = 1.0,
        lambda_laplacian: float = 0.0,
        lambda_temporal: float = 0.3,
        lambda_amplitude: float = 0.2,
        amplitude_max: float = 3.0,
    ):
        """
        Initialize physics-informed loss.

        Args:
            leadfield: Leadfield matrix (19, 76), typically from model buffers
            connectivity_laplacian: Connectivity Laplacian (76, 76)
            alpha: Weight for source reconstruction loss
            beta: Weight for forward consistency loss (variance-normalised,
                   so L_forward ≈ O(1). β=0.05 gives ~3% of total gradient
                   at init; increase to 0.1-0.2 if forward consistency is
                   underfitting the EEG.)
            gamma: Weight for physics regularization loss
            delta_epi: Weight for epileptogenic classification loss (class-balanced MSE)
            lambda_laplacian: Sub-weight for Laplacian regularization
            lambda_temporal: Sub-weight for temporal smoothness
            lambda_amplitude: Sub-weight for amplitude bound
            amplitude_max: Maximum allowed source amplitude (soft constraint)
        """
        super().__init__()

        # Register buffers for physics matrices (auto-moved with model.to(device))
        self.register_buffer('leadfield', leadfield)
        self.register_buffer('connectivity_laplacian', connectivity_laplacian)

        # Loss weights
        self.alpha = alpha
        self.beta = beta
        self.gamma = gamma
        self.delta_epi = delta_epi
        self.lambda_laplacian = lambda_laplacian
        self.lambda_temporal = lambda_temporal
        self.lambda_amplitude = lambda_amplitude
        self.amplitude_max = amplitude_max

        # MSE loss for supervised terms
        self.mse_loss = nn.MSELoss()
        logger.info(
            "PhysicsInformedLoss initialized with weights: "
            f"α={alpha}, β={beta}, γ={gamma}, δ_epi={delta_epi} | "
            f"λ_L={lambda_laplacian}, λ_T={lambda_temporal}, λ_A={lambda_amplitude} | "
            "L_forward variance-normalised, β adjusted for leadfield gradient amplification (~200×)"
        )

    def forward(
        self,
        predicted_sources: torch.Tensor,
        true_sources: torch.Tensor,
        eeg_input: torch.Tensor,
        epileptogenic_mask: Optional[torch.Tensor] = None,
        epoch: int = 0,
    ) -> Dict[str, torch.Tensor]:
        """
        Compute composite physics-informed loss.

        Args:
            predicted_sources: Predicted source activity (batch, 76, 400)
            true_sources: Ground truth source activity (batch, 76, 400)
            eeg_input: Input EEG measurements (batch, 19, 400)
            epileptogenic_mask: Boolean mask of epileptogenic regions (batch, 76)

        Returns:
            dict with keys:
            - 'loss_total': Total composite loss (scalar, ready to backprop)
            - 'loss_source': Source reconstruction loss (region-weighted)
            - 'loss_forward': Forward consistency loss (variance-normalised)
            - 'loss_laplacian': Laplacian regularization
            - 'loss_temporal': Temporal smoothness
            - 'loss_amplitude': Amplitude bound
            - 'loss_physics': Total physics loss (physics sub-losses combined)
            - 'loss_epi': Epileptogenic classification loss (class-balanced MSE)

        All loss terms are PyTorch scalars (single-element tensors).
        """
        # Loss 1: Source reconstruction (supervised, class-balanced)
        loss_source = self._compute_source_loss(
            predicted_sources, true_sources, epileptogenic_mask
        )

        # Loss 2: Forward consistency (physics, variance-normalised)
        loss_forward = self._compute_forward_loss(predicted_sources, eeg_input)

        # Loss 3: Physiological regularization
        loss_laplacian = self._compute_laplacian_loss(predicted_sources)
        loss_temporal = self._compute_temporal_loss(predicted_sources)
        loss_amplitude = self._compute_amplitude_loss(predicted_sources)

        # Combine physics sub-losses
        loss_physics = (
            self.lambda_laplacian * loss_laplacian
            + self.lambda_temporal * loss_temporal
            + self.lambda_amplitude * loss_amplitude
        )

        # Loss 4: Epileptogenic classification (class-balanced MSE on region power)
        loss_epi = self._compute_epi_loss(predicted_sources, epileptogenic_mask)

        # Warm-up: linearly ramp beta from 0 to target over first 5 epochs
        warmup_epochs = 5
        if epoch < warmup_epochs:
            beta_effective = self.beta * (epoch / warmup_epochs)
        else:
            beta_effective = self.beta

        # Composite total loss
        loss_total = (
            self.alpha * loss_source
            + beta_effective * loss_forward
            + self.gamma * loss_physics
            + self.delta_epi * loss_epi
        )

        return {
            'loss_total': loss_total,
            'loss_source': loss_source,
            'loss_forward': loss_forward,
            'loss_laplacian': loss_laplacian,
            'loss_temporal': loss_temporal,
            'loss_amplitude': loss_amplitude,
            'loss_physics': loss_physics,
            'loss_epi': loss_epi,
        }

    def _compute_source_loss(
        self,
        predicted_sources: torch.Tensor,
        true_sources: torch.Tensor,
        epileptogenic_mask: Optional[torch.Tensor] = None,
    ) -> torch.Tensor:
        """
        Compute source reconstruction loss (supervised MSE).

        L_source = (1/(N_r·T)) Σ_i Σ_t (Ŝ_{i,t} - S^true_{i,t})²

        When epileptogenic_mask is provided, applies per-region class-balancing
        weighting: epi-region MSE is up-weighted to match healthy-region total
        contribution, achieving equal gradient influence from both classes.

        Args:
            predicted_sources: (batch, 76, 400)
            true_sources: (batch, 76, 400)
            epileptogenic_mask: (batch, 76) bool mask, optional

        Returns:
            Scalar loss tensor
        """
        if epileptogenic_mask is None:
            return self.mse_loss(predicted_sources, true_sources)

        # Per-region MSE over time: (batch, 76)
        per_region_mse = ((predicted_sources - true_sources) ** 2).mean(dim=-1)

        # Compute per-sample class-balancing weight: n_healthy/n_epi
        n_epi = epileptogenic_mask.sum(dim=-1, keepdim=True).float().clamp(min=1.0)
        n_healthy = N_REGIONS - n_epi
        epi_weight = n_healthy / n_epi  # (batch, 1)

        # Build weight matrix: epi regions get high weight, healthy get 1.0
        weights = torch.ones_like(per_region_mse)
        epi_weight_expanded = epi_weight.expand_as(per_region_mse)
        weights[epileptogenic_mask] = epi_weight_expanded[epileptogenic_mask]

        # Weighted average over all (batch, region) pairs
        loss = (per_region_mse * weights).sum() / weights.sum()
        return loss

    def _compute_epi_loss(
        self,
        predicted_sources: torch.Tensor,
        epileptogenic_mask: Optional[torch.Tensor] = None,
    ) -> torch.Tensor:
        """
        Compute epileptogenic classification loss (class-balanced MSE on power).

        L_epi = weighted_MSE(mean_t(Ŝ²), target_mask)

        Uses MSE instead of BCEWithLogitsLoss because power = mean(Ŝ²) ≥ 0,
        so sigmoid(power) ≥ 0.5 always — healthy regions can never drop below
        chance with BCE. MSE directly pushes epi power toward 1.0 and healthy
        toward 0.0 with symmetric gradients.

        Class-balance weighting: epi regions (rare, ~2-8 per sample) are
        up-weighted by N_healthy/N_epi ≈ 10-50× so both classes contribute
        equally to the gradient despite class frequency.

        Args:
            predicted_sources: (batch, 76, 400)
            epileptogenic_mask: (batch, 76) bool mask; if None returns 0

        Returns:
            Scalar loss tensor
        """
        if epileptogenic_mask is None:
            return torch.tensor(0.0, device=predicted_sources.device)

        # Region power: (batch, 76) — always ≥ 0
        power = predicted_sources.pow(2).mean(dim=-1)
        target = epileptogenic_mask.float()  # 1 for epi, 0 for healthy

        # Per-region MSE: (batch, 76)
        per_region_mse = (power - target) ** 2

        # Class-balance weights: both classes contribute equally
        n_epi = epileptogenic_mask.sum(dim=-1, keepdim=True).float().clamp(min=1.0)
        n_healthy = N_REGIONS - n_epi
        weights = torch.ones_like(per_region_mse)
        epi_weight = n_healthy / n_epi  # ~10-50×
        epi_mask_expanded = epileptogenic_mask
        weights[epi_mask_expanded] = epi_weight.expand_as(weights)[epi_mask_expanded]

        loss = (per_region_mse * weights).sum() / weights.sum()
        return loss

    def _compute_forward_loss(
        self,
        predicted_sources: torch.Tensor,
        eeg_input: torch.Tensor,
    ) -> torch.Tensor:
        """
        Compute variance-normalised forward consistency loss.

        L_forward = MSE( AC(L @ Ŝ), EEG^input ) / (Var(EEG^input) + Var(L@Ŝ) + ε)

        where AC(·) denotes per-channel temporal de-meaning.

        Why normalise by BOTH Var(EEG) AND Var(L@Ŝ)?
        ──────────────────────────────────────────────
        Using either variance alone causes problems in one regime:

          Var(EEG) alone — Init with random Ŝ:  raw_mse ≈ Var(L@Ŝ) + Var(EEG)
          so L_forward ≈ (Var(L@Ŝ) + 1) / 1 ≈ 600× too large.  The ~200×
          leadfield RMS amplification makes raw_mse≫Var(EEG) at init.

          Var(L@Ŝ) alone — If gradient collapse forces Ŝ≈0, Var(L@Ŝ)≈0 →
          L_forward = Var(EEG) / 1e-7 ≈ 1e7, locking the model at L^T@EEG.

          BOTH — At init, denom ≈ Var(L@Ŝ) + 1 ≈ raw_mse ⇒ L_forward ≈ 1.
          If Ŝ≈0, denom ≈ 0 + 1 = 1 ⇒ L_forward ≈ Var(EEG)/1 ≈ 1.
          Robust in ALL regimes ✓

        Why de-mean eeg_predicted?
        ──────────────────────────
        EEG input is per-channel de-meaned before z-scoring (DC removed).
        Per-region de-meaning of sources commutes with the leadfield
        (mean(L@Ŝ) = L@mean(Ŝ)), so for perfectly de-meaned Ŝ the forward
        projection is already DC-free.  However during early training Ŝ
        carries non-zero per-region DC offsets that the leadfield mixes into
        per-channel DC in the forward projection.  De-meaning eeg_predicted
        removes this spurious DC mismatch from the MSE so the gradient only
        reflects AC dynamics — matching clinical reality where EEG hardware
        applies High-pass filters before digitisation.

        Args:
            predicted_sources: (batch, 76, 400)
            eeg_input: (batch, 19, 400)

        Returns:
            Scalar loss tensor (dimensionless, ≈ O(1) throughout training)
        """
        # Project predicted sources through leadfield
        # leadfield: (19, 76); predicted_sources: (batch, 76, 400)
        # eeg_predicted: (batch, 19, 400)
        eeg_predicted = torch.einsum(
            'ij,bjk->bik', self.leadfield, predicted_sources
        )

        # ── Per-channel temporal de-meaning on forward prediction ──
        # EEG input is per-channel de-meaned (DC removed) before z-scoring.
        # For perfectly de-meaned sources (mean(Ŝ)=0 per region), the leadfield
        # projection preserves zero DC: mean(L@Ŝ)=L@mean(Ŝ)=0 per channel.
        #
        # In early training, predicted sources carry non-zero per-region DC
        # offsets that the leadfield mixes into per-channel DC in eeg_predicted.
        # Without de-meaning here, the MSE penalises this DC mismatch — a
        # spurious gradient that does not improve source reconstruction.  This
        # is also physically correct: clinical EEG is AC-coupled by hardware
        # high-pass filters, so only AC dynamics should be compared.
        eeg_predicted = eeg_predicted - eeg_predicted.mean(dim=-1, keepdim=True)

        # Raw MSE between forward prediction and target EEG
        raw_mse = ((eeg_predicted - eeg_input) ** 2).mean()

        # ── Stable variance-normalised denominator ──
        # Denom = Var(EEG_target) + Var(L@Ŝ) + ε
        #
        # Var(EEG) ≈ 1.0 after z-scoring — prevents blow-up when Ŝ≈0.
        # Var(L@Ŝ) ≈ raw_mse at init (Ŝ random) — cancels leadfield
        # amplification (~200×) so L_forward ≈ O(1) even when model
        # outputs are not near zero.
        #
        # Using EITHER alone fails:
        #   Var(EEG) alone:  L_forward≈600 at init (Ŝ≈0.13 → L@Ŝ std≈25)
        #   Var(L@Ŝ) alone: L_forward≈1 at init BUT blows to 1e7 if Ŝ≈0
        #   BOTH:            L_forward≈1 at BOTH extremes ✓
        eeg_var = eeg_input.var().detach()
        fwd_var = eeg_predicted.var().detach()
        loss = raw_mse / (eeg_var + fwd_var + _EPS)

        return loss

    def _compute_laplacian_loss(
        self,
        predicted_sources: torch.Tensor,
    ) -> torch.Tensor:
        """
        Compute Laplacian regularization loss (spatial smoothness).

        L_Laplacian = (1/(N_r·T)) Σ_t Ŝ_t^T @ D @ Ŝ_t

        where D is the graph Laplacian of the structural connectivity matrix.
        Penalises large mismatches between activity in connected regions,
        encouraging spatially smooth source estimates consistent with the
        underlying brain connectivity.

        Vectorised implementation (no Python loop over T):
          D @ Ŝ  →  einsum('ij,bjt->bit', D, Ŝ)   shape (batch, 76, 400)
          Ŝ ⊙ (D @ Ŝ)  →  element-wise product, then sum over region dim
          Mean over batch and time gives the scalar loss.

        Args:
            predicted_sources: (batch, 76, 400)

        Returns:
            Scalar loss tensor (averaged over batch, regions, and time)
        """
        # D @ Ŝ for every batch element and time step simultaneously
        # connectivity_laplacian: (76, 76); predicted_sources: (batch, 76, 400)
        # d_sources: (batch, 76, 400)
        d_sources = torch.einsum(
            'ij,bjt->bit', self.connectivity_laplacian, predicted_sources
        )

        # Quadratic form: Ŝ^T @ D @ Ŝ per batch element and time step
        # = element-wise product Ŝ ⊙ (D @ Ŝ), summed over region dimension
        # quad_form shape: (batch, 400)
        quad_form = (predicted_sources * d_sources).sum(dim=1)  # (batch, T)

        # Mean over batch and time for a normalised scalar
        loss = quad_form.mean()

        return loss

    def _compute_temporal_loss(
        self,
        predicted_sources: torch.Tensor,
    ) -> torch.Tensor:
        """
        Compute temporal smoothness loss.

        L_temporal = (1/(N_r·(T-1))) Σ_i Σ_t (Ŝ_{i,t+1} - Ŝ_{i,t})²

        Penalises high-frequency jitter in the source time courses,
        encouraging smooth temporal evolution consistent with slowly-
        varying cortical activity.

        Args:
            predicted_sources: (batch, 76, 400)

        Returns:
            Scalar loss tensor (averaged over regions, time, and batch)
        """
        # Consecutive time-point differences: (batch, 76, 399)
        temporal_diff = predicted_sources[:, :, 1:] - predicted_sources[:, :, :-1]
        return torch.mean(temporal_diff ** 2)

    def _compute_amplitude_loss(
        self,
        predicted_sources: torch.Tensor,
    ) -> torch.Tensor:
        """
        Compute amplitude bound loss (soft physiological constraint).

        L_amplitude = (1/(N_r·T)) Σ_{i,t} max(0, |Ŝ_{i,t}| - A_max)²

        Soft constraint penalising source amplitudes exceeding A_max
        (default 3.0, after z-score normalisation).  Values within bounds
        contribute zero loss; only violations are penalised.

        Args:
            predicted_sources: (batch, 76, 400)

        Returns:
            Scalar loss tensor
        """
        violations = torch.clamp(
            torch.abs(predicted_sources) - self.amplitude_max,
            min=0.0,
        )
        return torch.mean(violations ** 2)
