"""
Module: loss_functions.py
Phase: 2 — PhysDeepSIF Network Architecture and Training
Purpose: Implement physics-informed composite loss function for PhysDeepSIF.

This module implements the three-component loss function specified in Technical
Specs Section 4.2:
  1. Source reconstruction loss (supervised MSE)
  2. Forward consistency loss (using leadfield)
  3. Physiological regularization loss (Laplacian, temporal, amplitude)

The composite loss is:
    L_total = α·L_source + β·L_forward + γ·L_physics

where L_physics = λ1·L_Laplacian + λ2·L_temporal + λ3·L_amplitude

This design encourages the network to learn source estimates that are:
- Faithful to the ground truth source activity (L_source)
- Consistent with the physics of EEG generation (L_forward via leadfield)
- Biologically realistic with spatial/temporal smoothness (L_physics)

Key dependencies:
- torch: Neural network framework
- numpy: Numerical operations

Input data format:
- predicted_sources: (batch, 76, 400) predicted source activity
- true_sources: (batch, 76, 400) ground truth source activity
- eeg_input: (batch, 19, 400) input EEG measurements
- leadfield: (19, 76) forward model matrix
- connectivity_laplacian: (76, 76) Laplacian of connectivity

Author: Generated by GitHub Copilot
Date: 2026-02-18
"""

import logging
from typing import Dict

import torch
import torch.nn as nn

logger = logging.getLogger(__name__)

# Module-level constants
N_REGIONS = 76
N_CHANNELS = 19
WINDOW_LENGTH_SAMPLES = 400


class PhysicsInformedLoss(nn.Module):
    """
    Composite physics-informed loss function for PhysDeepSIF.
    
    This loss combines three components to guide network training:
    
    1. **Source Reconstruction Loss (L_source)**:
       MSE between predicted and ground truth source activity.
       Directly supervised signal; encourages accurate source estimation.
       
       L_source = (1/(N_r·T)) Σ_i Σ_t (Ŝ_{i,t} - S^true_{i,t})²
       
    2. **Forward Consistency Loss (L_forward)**:
       MSE between the leadfield-projected prediction and input EEG.
       Ensures predicted sources are consistent with physics of EEG generation.
       
       L_forward = (1/(N_c·T)) Σ_j Σ_t (L @ Ŝ_t - EEG^input_t)²_j
       
    3. **Physiological Regularization Loss (L_physics)**:
       Three sub-components enforcing biological realism:
       
       a) Laplacian regularization (spatial smoothness):
          L_Laplacian = (1/T) Σ_t Ŝ_t^T @ D @ Ŝ_t
          where D is the graph Laplacian (connectivity-based smoothness)
       
       b) Temporal smoothness (penalize high-frequency jitter):
          L_temporal = (1/(N_r·(T-1))) Σ_i Σ_t (Ŝ_{i,t+1} - Ŝ_{i,t})²
       
       c) Amplitude bound (soft physiological constraint):
          L_amplitude = (1/(N_r·T)) Σ_{i,t} max(0, |Ŝ_{i,t}| - A_max)²
          where A_max = 3.0 (after normalization)
       
       L_physics = λ1·L_Laplacian + λ2·L_temporal + λ3·L_amplitude
    
    Total loss:
        L_total = α·L_source + β·L_forward + γ·L_physics
    
    Default weights (from Technical Specs Section 4.2.5):
    - α = 1.0 (source reconstruction)
    - β = 0.5 (forward consistency)
    - γ = 0.1 (physics regularization)
    - λ1 = 0.5 (Laplacian)
    - λ2 = 0.3 (temporal)
    - λ3 = 0.2 (amplitude)
    """
    
    def __init__(
        self,
        leadfield: torch.Tensor,
        connectivity_laplacian: torch.Tensor,
        alpha: float = 1.0,
        beta: float = 0.5,
        gamma: float = 0.1,
        lambda_laplacian: float = 0.5,
        lambda_temporal: float = 0.3,
        lambda_amplitude: float = 0.2,
        amplitude_max: float = 3.0,
    ):
        """
        Initialize physics-informed loss.
        
        Args:
            leadfield: Leadfield matrix (19, 76), typically from model buffers
            connectivity_laplacian: Connectivity Laplacian (76, 76)
            alpha: Weight for source reconstruction loss
            beta: Weight for forward consistency loss
            gamma: Weight for physics regularization loss
            lambda_laplacian: Sub-weight for Laplacian regularization (relative to gamma)
            lambda_temporal: Sub-weight for temporal smoothness (relative to gamma)
            lambda_amplitude: Sub-weight for amplitude bound (relative to gamma)
            amplitude_max: Maximum allowed source amplitude (soft constraint)
        """
        super().__init__()
        
        # Register buffers for physics matrices
        self.register_buffer('leadfield', leadfield)
        self.register_buffer('connectivity_laplacian', connectivity_laplacian)
        
        # Loss weights
        self.alpha = alpha
        self.beta = beta
        self.gamma = gamma
        self.lambda_laplacian = lambda_laplacian
        self.lambda_temporal = lambda_temporal
        self.lambda_amplitude = lambda_amplitude
        self.amplitude_max = amplitude_max
        
        # MSE loss for supervised terms
        self.mse_loss = nn.MSELoss()
        
        logger.info(
            f"PhysicsInformedLoss initialized with weights: "
            f"α={alpha}, β={beta}, γ={gamma} | "
            f"λ_L={lambda_laplacian}, λ_T={lambda_temporal}, λ_A={lambda_amplitude}"
        )
    
    def forward(
        self,
        predicted_sources: torch.Tensor,
        true_sources: torch.Tensor,
        eeg_input: torch.Tensor,
    ) -> Dict[str, torch.Tensor]:
        """
        Compute composite physics-informed loss.
        
        Args:
            predicted_sources: Predicted source activity (batch, 76, 400)
            true_sources: Ground truth source activity (batch, 76, 400)
            eeg_input: Input EEG measurements (batch, 19, 400)
        
        Returns:
            dict with keys:
            - 'loss_total': Total composite loss (scalar, ready to backprop)
            - 'loss_source': Source reconstruction loss
            - 'loss_forward': Forward consistency loss
            - 'loss_laplacian': Laplacian regularization
            - 'loss_temporal': Temporal smoothness
            - 'loss_amplitude': Amplitude bound
            - 'loss_physics': Total physics loss (physics sub-losses combined)
        
        All loss terms are PyTorch scalars (single-element tensors).
        """
        # Loss 1: Source reconstruction (supervised)
        loss_source = self._compute_source_loss(predicted_sources, true_sources)
        
        # Loss 2: Forward consistency (physics)
        loss_forward = self._compute_forward_loss(predicted_sources, eeg_input)
        
        # Loss 3: Physiological regularization
        loss_laplacian = self._compute_laplacian_loss(predicted_sources)
        loss_temporal = self._compute_temporal_loss(predicted_sources)
        loss_amplitude = self._compute_amplitude_loss(predicted_sources)
        
        # Combine physics sub-losses
        loss_physics = (
            self.lambda_laplacian * loss_laplacian
            + self.lambda_temporal * loss_temporal
            + self.lambda_amplitude * loss_amplitude
        )
        
        # Composite total loss
        loss_total = (
            self.alpha * loss_source
            + self.beta * loss_forward
            + self.gamma * loss_physics
        )
        
        return {
            'loss_total': loss_total,
            'loss_source': loss_source,
            'loss_forward': loss_forward,
            'loss_laplacian': loss_laplacian,
            'loss_temporal': loss_temporal,
            'loss_amplitude': loss_amplitude,
            'loss_physics': loss_physics,
        }
    
    def _compute_source_loss(
        self,
        predicted_sources: torch.Tensor,
        true_sources: torch.Tensor,
    ) -> torch.Tensor:
        """
        Compute source reconstruction loss (supervised MSE).
        
        L_source = (1/(N_r·T)) Σ_i Σ_t (Ŝ_{i,t} - S^true_{i,t})²
        
        This directly compares predicted source activity to ground truth,
        providing the main supervised training signal.
        
        Args:
            predicted_sources: (batch, 76, 400)
            true_sources: (batch, 76, 400)
        
        Returns:
            Scalar loss tensor
        """
        return self.mse_loss(predicted_sources, true_sources)
    
    def _compute_forward_loss(
        self,
        predicted_sources: torch.Tensor,
        eeg_input: torch.Tensor,
    ) -> torch.Tensor:
        """
        Compute forward consistency loss.
        
        L_forward = (1/(N_c·T)) Σ_j Σ_t (L @ Ŝ_t - EEG^input_t)²_j
        
        where L is the leadfield matrix. This ensures that when the predicted
        sources are projected through the forward model, they produce EEG
        signals consistent with the input. This is a physics constraint.
        
        Implementation:
          1. For each time step: multiply leadfield (19×76) @ sources (76,)
          2. Compute MSE between EEG projection and input
        
        Args:
            predicted_sources: (batch, 76, 400)
            eeg_input: (batch, 19, 400)
        
        Returns:
            Scalar loss tensor
        """
        # Project predicted sources through leadfield
        # leadfield: (19, 76)
        # predicted_sources: (batch, 76, 400)
        # We want: (batch, 19, 400)
        
        # Reshape for batch matrix multiplication
        batch_size, n_regions, n_time = predicted_sources.shape
        
        # Flatten: (batch, 76, 400) → (batch, 76*400) = (batch, 30400)
        sources_flat = predicted_sources.reshape(batch_size, -1)
        
        # Apply leadfield to flattened time series is not correct.
        # Instead, for each time point, apply leadfield separately.
        
        # Better approach: use einsum or batch multiply
        # leadfield (19, 76) @ sources (batch, 76, 400) → (batch, 19, 400)
        # einsum: 'ij,bjk->bik'
        eeg_predicted = torch.einsum('ij,bjk->bik', self.leadfield, predicted_sources)
        
        # MSE between predicted EEG and input EEG
        loss = self.mse_loss(eeg_predicted, eeg_input)
        
        return loss
    
    def _compute_laplacian_loss(
        self,
        predicted_sources: torch.Tensor,
    ) -> torch.Tensor:
        """
        Compute Laplacian regularization loss (spatial smoothness).
        
        L_Laplacian = (1/T) Σ_t Ŝ_t^T @ D @ Ŝ_t
        
        where D is the graph Laplacian of the structural connectivity matrix.
        This penalizes large mismatches between activity levels in connected
        regions, encouraging spatially smooth source estimates consistent with
        the underlying brain connectivity.
        
        Mathematical interpretation:
        - D @ Ŝ_t emphasizes differences between neighboring regions
        - The quadratic form Ŝ_t^T @ D @ Ŝ_t is minimized when activity
          in neighboring regions is similar
        
        Args:
            predicted_sources: (batch, 76, 400)
        
        Returns:
            Scalar loss tensor (averaged over time and batch)
        """
        # connectivity_laplacian: (76, 76)
        # predicted_sources: (batch, 76, 400)
        
        # For each time point, compute s_t^T @ D @ s_t
        batch_size, n_regions, n_time = predicted_sources.shape
        
        loss = torch.tensor(0.0, device=predicted_sources.device)
        
        # Iterate over time (could also vectorize with einsum)
        for t in range(n_time):
            sources_t = predicted_sources[:, :, t]  # (batch, 76)
            
            # Compute Laplacian contribution: sources @ D @ sources
            # D @ sources: (76, 76) @ (batch, 76) → (batch, 76)
            d_sources = torch.matmul(self.connectivity_laplacian, sources_t.t()).t()  # (batch, 76)
            
            # sources^T @ D @ sources for each batch element
            quad_form = (sources_t * d_sources).sum(dim=1)  # (batch,)
            
            loss = loss + quad_form.mean()
        
        # Normalize by number of time points
        loss = loss / n_time
        
        return loss
    
    def _compute_temporal_loss(
        self,
        predicted_sources: torch.Tensor,
    ) -> torch.Tensor:
        """
        Compute temporal smoothness loss.
        
        L_temporal = (1/(N_r·(T-1))) Σ_i Σ_t (Ŝ_{i,t+1} - Ŝ_{i,t})²
        
        This penalizes high-frequency jitter in the source time courses,
        encouraging smooth temporal evolution consistent with slowly-
        varying cortical activity.
        
        Args:
            predicted_sources: (batch, 76, 400)
        
        Returns:
            Scalar loss tensor (averaged over regions, time, and batch)
        """
        # Compute differences between consecutive time points
        # sources[:, :, 1:] - sources[:, :, :-1]: (batch, 76, 399)
        temporal_diff = predicted_sources[:, :, 1:] - predicted_sources[:, :, :-1]
        
        # MSE of temporal differences
        loss = torch.mean(temporal_diff ** 2)
        
        return loss
    
    def _compute_amplitude_loss(
        self,
        predicted_sources: torch.Tensor,
    ) -> torch.Tensor:
        """
        Compute amplitude bound loss (soft physiological constraint).
        
        L_amplitude = (1/(N_r·T)) Σ_{i,t} max(0, |Ŝ_{i,t}| - A_max)²
        
        This is a soft constraint that penalizes source amplitudes exceeding
        A_max (typically 3.0 after normalization). It encourages realistic
        source magnitudes without hard thresholding.
        
        The max(0, ·) makes this a one-sided constraint: violations are
        penalized, but values within bounds contribute zero loss.
        
        Args:
            predicted_sources: (batch, 76, 400)
        
        Returns:
            Scalar loss tensor
        """
        # Compute violations: max(0, |sources| - A_max)
        violations = torch.clamp(
            torch.abs(predicted_sources) - self.amplitude_max,
            min=0.0,
        )
        
        # MSE of violations
        loss = torch.mean(violations ** 2)
        
        return loss
