"""
Module: metrics.py
Phase: 2 — PhysDeepSIF Network Architecture and Training
Purpose: Validation metrics for source imaging inverse problem.

This module implements all metrics specified in Technical Specs Section 4.3.3:
- Dipole Localization Error (DLE): Euclidean distance between power-weighted
  centroids of predicted and true source activity (target: < 20 mm)
- Spatial Dispersion (SD): Spatial extent of epileptogenic zone estimate
  (target: < 30 mm)
- Area Under ROC (AUC): Classification metric for epileptogenicity
  (target: > 0.85)
- Temporal Correlation: Pearson correlation between predicted and true
  source time series (target: > 0.7)

All metrics are computed on the validation set to assess model generalization
and physical plausibility of predictions.

Key dependencies:
- numpy: Numerical operations
- sklearn.metrics: ROC AUC computation

Author: Generated by GitHub Copilot
Date: 2026-02-18
"""

import logging
from typing import Tuple

import numpy as np
from numpy.typing import NDArray
from sklearn.metrics import roc_auc_score

logger = logging.getLogger(__name__)

# Module-level constants
N_REGIONS = 76
SPATIAL_COORD_DIM = 3  # x, y, z coordinates


def compute_dipole_localization_error(
    predicted_sources: NDArray[np.float32],
    true_sources: NDArray[np.float32],
    region_centers: NDArray[np.float32],
) -> float:
    """
    Compute Dipole Localization Error (DLE) between predicted and true sources.
    
    DLE measures the Euclidean distance between the power-weighted centroid of
    the predicted source activity and the true epileptogenic center. This is a
    standard metric in EEG source imaging (Molins et al., 2008) that indicates
    how accurately we localize the seizure focus.
    
    Algorithm:
        1. Compute time-averaged power for each region:
           power_i = mean(source_i(t)^2)
        2. Compute power-weighted centroid:
           centroid = Σ_i (power_i * center_i) / Σ_i power_i
        3. Euclidean distance between predicted and true centroids
    
    Args:
        predicted_sources: Predicted source activity, shape (batch, 76, 400)
            - Expected range: normalized, typically [-3, +3] after z-scoring
            - Units: arbitrary normalized units
        true_sources: Ground truth source activity, shape (batch, 76, 400)
            - Same format as predicted_sources
        region_centers: 3D coordinates of region centroids, shape (76, 3)
            - Units: millimeters (mm), MNI space
            - Expected coordinate range: brain space (±100mm from center)
    
    Returns:
        float: Average DLE across batch in millimeters. Lower is better.
        Target threshold: < 20 mm (Molins et al., 2008)
    
    Raises:
        ValueError: If shapes don't match specification
        RuntimeError: If all power is zero (degenerate source localization)
    
    References:
        Molins et al. (2008): "Kernel on integrated functional spaces for
        enhanced source imaging with EEG/MEG" NeuroImage.
        Technical Specs Section 4.3.3.
    
    Example:
        >>> pred_sources = np.random.randn(10, 76, 400).astype(np.float32)
        >>> true_sources = np.random.randn(10, 76, 400).astype(np.float32)
        >>> centers = np.random.randn(76, 3).astype(np.float32) * 50
        >>> dle = compute_dipole_localization_error(pred_sources, true_sources, centers)
        >>> print(f"DLE: {dle:.2f} mm")
    """
    # Validate input shapes
    if predicted_sources.shape != true_sources.shape:
        raise ValueError(
            f"Shape mismatch: predicted {predicted_sources.shape} vs "
            f"true {true_sources.shape}"
        )
    
    if predicted_sources.shape[1] != N_REGIONS:
        raise ValueError(
            f"Expected {N_REGIONS} regions, got {predicted_sources.shape[1]}"
        )
    
    if region_centers.shape != (N_REGIONS, SPATIAL_COORD_DIM):
        raise ValueError(
            f"Region centers shape mismatch: expected ({N_REGIONS}, 3), "
            f"got {region_centers.shape}"
        )
    
    batch_size = predicted_sources.shape[0]
    dle_values = []
    
    for sample_idx in range(batch_size):
        # Step 1: Extract source time series for this sample
        # Shape: (76, 400)
        pred_ts = predicted_sources[sample_idx]  
        true_ts = true_sources[sample_idx]
        
        # Step 2: Compute time-averaged power for each region
        # Power = mean of squared activity across time dimension
        # Shape: (76,)
        # Interpretation: higher power indicates stronger/more sustained activity
        pred_power = np.mean(pred_ts ** 2, axis=1)  
        true_power = np.mean(true_ts ** 2, axis=1)
        
        # Step 3: Compute power-weighted centroid of predicted sources
        # This represents the "center of mass" of the predicted epileptogenic zone
        # weighted by source strength at each region
        total_pred_power = np.sum(pred_power)  # Normalization factor
        
        if total_pred_power < 1e-10:
            # Degenerate case: no predicted activity
            # Use uniform weighting fallback (geometric center)
            pred_centroid = np.mean(region_centers, axis=0)
        else:
            # Weighted average of region positions by their power
            # Formula: centroid = Σ(power_i * center_i) / Σ(power_i)
            # Broadcasting: (76, 1) * (76, 3) = (76, 3) → sum over regions → (3,)
            pred_centroid = np.sum(
                pred_power[:, np.newaxis] * region_centers, axis=0
            ) / total_pred_power
        
        # Step 4: Compute true epileptogenic centroid (same method)
        total_true_power = np.sum(true_power)
        
        if total_true_power < 1e-10:
            # Degenerate case: no true activity
            true_centroid = np.mean(region_centers, axis=0)
        else:
            true_centroid = np.sum(
                true_power[:, np.newaxis] * region_centers, axis=0
            ) / total_true_power
        
        # Step 5: Euclidean distance between the two centroids
        # This is our DLE metric - how far off was our spatial localization?
        dle = np.linalg.norm(pred_centroid - true_centroid)  # Distance in mm
        dle_values.append(dle)
    
    # Return average DLE across batch
    avg_dle = np.mean(dle_values)
    return float(avg_dle)


def compute_spatial_dispersion(
    source_estimate: NDArray[np.float32],
    region_centers: NDArray[np.float32],
) -> float:
    """
    Compute Spatial Dispersion (SD) of source localization.
    
    SD measures the spatial spread/extent of the estimated epileptogenic zone.
    A small SD indicates a focal/localized seizure focus (good for surgical
    candidate selection). A large SD indicates diffuse activity (widespread
    epileptogenicity).
    
    Algorithm:
        1. Compute time-averaged power per region
        2. Compute power-weighted centroid
        3. Compute weighted spatial variance around centroid:
           SD = sqrt(Σ_i power_i * distance(center_i, centroid)^2 / Σ_i power_i)
    
    Args:
        source_estimate: Estimated source activity, shape (batch, 76, 400)
            - Same format as compute_dipole_localization_error
        region_centers: 3D region coordinates, shape (76, 3), in mm
    
    Returns:
        float: Average spatial dispersion across batch in millimeters.
        Lower is better (more focal).
        Target threshold: < 30 mm (focal seizure focus)
    
    Raises:
        ValueError: If shapes don't match
    
    References:
        Technical Specs Section 4.3.3.
    
    Example:
        >>> sources = np.random.randn(10, 76, 400).astype(np.float32)
        >>> centers = np.random.randn(76, 3).astype(np.float32) * 50
        >>> sd = compute_spatial_dispersion(sources, centers)
        >>> print(f"Spatial Dispersion: {sd:.2f} mm")
    """
    # Validate inputs
    if source_estimate.shape[1] != N_REGIONS:
        raise ValueError(
            f"Expected {N_REGIONS} regions, got {source_estimate.shape[1]}"
        )
    
    if region_centers.shape != (N_REGIONS, SPATIAL_COORD_DIM):
        raise ValueError(
            f"Region centers shape mismatch: expected ({N_REGIONS}, 3), "
            f"got {region_centers.shape}"
        )
    
    batch_size = source_estimate.shape[0]
    sd_values = []
    
    for sample_idx in range(batch_size):
        # Extract source time series
        source_ts = source_estimate[sample_idx]  # (76, 400)
        
        # Compute power per region
        power = np.mean(source_ts ** 2, axis=1)  # (76,)
        total_power = np.sum(power)
        
        if total_power < 1e-10:
            # Degenerate case: use uniform weighting
            centroid = np.mean(region_centers, axis=0)
        else:
            # Compute weighted centroid
            centroid = np.sum(
                power[:, np.newaxis] * region_centers, axis=0
            ) / total_power
        
        # Compute power-weighted variance around centroid
        # Distance from each region center to the centroid
        distances = np.linalg.norm(region_centers - centroid[np.newaxis, :], axis=1)
        
        # Weighted variance: Σ(power_i * distance_i^2) / Σ(power_i)
        weighted_variance = np.sum(power * distances ** 2) / (total_power + 1e-10)
        
        # Standard deviation (spatial dispersion)
        sd = np.sqrt(weighted_variance)
        sd_values.append(sd)
    
    # Return average SD across batch
    avg_sd = np.mean(sd_values)
    return float(avg_sd)


def compute_auc_epileptogenicity(
    source_estimate: NDArray[np.float32],
    epileptogenic_mask: NDArray[np.bool_],
) -> float:
    """
    Compute Area Under ROC curve for epileptogenicity classification.
    
    This metric evaluates whether high source activity predicts the true
    epileptogenic regions. We create a binary classification task: for each
    region in each sample, we predict whether it's in the epileptogenic zone
    based on mean source power.
    
    Algorithm:
        1. Compute time-averaged power per region (univariate feature)
        2. Flatten: shape (batch * 76,) for ROC curve computation
        3. Create binary labels: epileptogenic_mask flattened to (batch * 76,)
        4. Compute AUC using sklearn.metrics.roc_auc_score
    
    Args:
        source_estimate: Estimated source activity, shape (batch, 76, 400)
            - Expected range: normalized units after z-scoring
        epileptogenic_mask: Ground truth binary labels, shape (batch, 76)
            - True for regions in epileptogenic zone, False otherwise
            - Typically ~1-3 regions per sample are epileptogenic
    
    Returns:
        float: Area Under ROC curve in [0, 1]. Higher is better.
        Target threshold: > 0.85
        - 1.0 = perfect classification
        - 0.5 = random classifier
        - < 0.5 = worse than random (usually indicates label/feature inversion)
    
    Raises:
        ValueError: If shapes don't match
        RuntimeError: If all labels are the same (no positive/negative samples)
    
    References:
        Technical Specs Section 4.3.3.
    
    Example:
        >>> sources = np.random.randn(10, 76, 400).astype(np.float32)
        >>> mask = np.zeros((10, 76), dtype=bool)
        >>> mask[:, 10:15] = True  # Regions 10-14 are epileptogenic
        >>> auc = compute_auc_epileptogenicity(sources, mask)
        >>> print(f"AUC: {auc:.3f}")
    """
    # Validate inputs
    if source_estimate.shape[:2] != epileptogenic_mask.shape:
        raise ValueError(
            f"Shape mismatch: source {source_estimate.shape[:2]} vs "
            f"mask {epileptogenic_mask.shape}"
        )
    
    if source_estimate.shape[1] != N_REGIONS:
        raise ValueError(
            f"Expected {N_REGIONS} regions, got {source_estimate.shape[1]}"
        )
    
    # Step 1: Compute time-averaged power per region
    # Shape: (batch, 76, 400) → (batch, 76)
    power = np.mean(source_estimate ** 2, axis=2)
    
    # Step 2: Flatten for sklearn (batch * 76,)
    power_flat = power.flatten()
    labels_flat = epileptogenic_mask.flatten()
    
    # Step 3: Check for degenerate labels (all same class)
    unique_labels = np.unique(labels_flat)
    if len(unique_labels) < 2:
        # All samples have same label (all epileptogenic or all not)
        # ROC curve not defined; return 0.5 (random baseline)
        logger.warning(
            f"All labels are the same ({unique_labels}). "
            "AUC is undefined; returning 0.5."
        )
        return 0.5
    
    # Step 4: Compute AUC via sklearn
    try:
        auc = roc_auc_score(labels_flat, power_flat)
        return float(auc)
    except Exception as e:
        logger.error(f"Error computing AUC: {e}")
        return 0.5


def compute_temporal_correlation(
    predicted_sources: NDArray[np.float32],
    true_sources: NDArray[np.float32],
) -> float:
    """
    Compute Pearson temporal correlation between predicted and true sources.
    
    This metric measures how well predicted source time dynamics match the
    ground truth. High correlation indicates the model captures the temporal
    structure of seizure evolution.
    
    Algorithm:
        1. For each region and sample: compute Pearson correlation across time
        2. Average correlations across regions and batch
    
    Args:
        predicted_sources: Predicted activity, shape (batch, 76, 400)
            - Expected range: normalized units after z-scoring
        true_sources: Ground truth activity, shape (batch, 76, 400)
            - Same format as predicted
    
    Returns:
        float: Average Pearson correlation in [-1, 1]. Higher is better.
        Target threshold: > 0.7
        - 1.0 = perfect positivelinear correlation
        - 0.0 = no linear correlation
        - -1.0 = perfect negative linear correlation
    
    Raises:
        ValueError: If shapes don't match
    
    References:
        Technical Specs Section 4.3.3.
    
    Example:
        >>> pred = np.random.randn(10, 76, 400).astype(np.float32)
        >>> true = np.random.randn(10, 76, 400).astype(np.float32)
        >>> corr = compute_temporal_correlation(pred, true)
        >>> print(f"Correlation: {corr:.3f}")
    """
    # Validate inputs
    if predicted_sources.shape != true_sources.shape:
        raise ValueError(
            f"Shape mismatch: predicted {predicted_sources.shape} vs "
            f"true {true_sources.shape}"
        )
    
    if predicted_sources.shape[1] != N_REGIONS:
        raise ValueError(
            f"Expected {N_REGIONS} regions, got {predicted_sources.shape[1]}"
        )
    
    batch_size, n_regions, n_samples = predicted_sources.shape
    correlations = []
    
    # For each sample and region, compute correlation across time
    for sample_idx in range(batch_size):
        for region_idx in range(n_regions):
            pred_ts = predicted_sources[sample_idx, region_idx, :]  # (400,)
            true_ts = true_sources[sample_idx, region_idx, :]      # (400,)
            
            # Pearson correlation: numpy.corrcoef returns 2x2 matrix
            # [0, 1] is correlation between the two time series
            try:
                corr_matrix = np.corrcoef(pred_ts, true_ts)
                corr = corr_matrix[0, 1]  # Off-diagonal element
                
                # Handle NaN (occurs when one time series has zero variance)
                if not np.isnan(corr):
                    correlations.append(corr)
            except Exception:
                # Skip if correlation can't be computed
                pass
    
    # Return average correlation across all valid pairs
    if len(correlations) == 0:
        # All time series had zero variance; return 0 (no meaningful correlation)
        logger.warning("All correlation values were NaN; returning 0.0")
        return 0.0
    
    avg_corr = np.mean(correlations)
    return float(avg_corr)


if __name__ == "__main__":
    # Quick test of all metrics
    print("Testing metrics module...")
    
    # Create dummy data
    batch_size = 4
    n_regions = 76
    n_times = 400
    
    pred_sources = np.random.randn(batch_size, n_regions, n_times).astype(np.float32)
    true_sources = np.random.randn(batch_size, n_regions, n_times).astype(np.float32)
    region_centers = np.random.randn(n_regions, 3).astype(np.float32) * 50
    epileptogenic_mask = np.zeros((batch_size, n_regions), dtype=bool)
    epileptogenic_mask[:, 10:15] = True
    
    # Test each metric
    dle = compute_dipole_localization_error(pred_sources, true_sources, region_centers)
    print(f"✓ DLE: {dle:.2f} mm")
    
    sd = compute_spatial_dispersion(pred_sources, region_centers)
    print(f"✓ SD: {sd:.2f} mm")
    
    auc = compute_auc_epileptogenicity(pred_sources, epileptogenic_mask)
    print(f"✓ AUC: {auc:.3f}")
    
    corr = compute_temporal_correlation(pred_sources, true_sources)
    print(f"✓ Correlation: {corr:.3f}")
    
    print("\nAll metrics computed successfully!")
