"""
Module: physdeepsif.py
Phase: 2 — PhysDeepSIF Network Architecture and Training
Purpose: Implement the PhysDeepSIF neural network architecture, adapted from
         DeepSIF (Sun et al., 2022, PNAS) for 76-region parcellated source space.

This module implements a physics-informed deep learning network that maps
19-channel EEG to 76-region source activity. The network has two main
components:
  1. Spatial Module: MLP that processes each time step independently
  2. Temporal Module: BiLSTM layers that enforce temporal consistency

The network is designed to integrate with a physics-informed loss function
that includes forward consistency and structural regularization terms.

Key properties:
- Input: EEG tensor (batch, 19, 400) — 19 channels, 400 time points (2 sec)
- Output: Source estimate (batch, 76, 400) — 76 brain regions, 2 sec
- Leadfield matrix (19×76) registered as non-trainable buffer
- Connectivity Laplacian (76×76) registered as non-trainable buffer
- Total parameters: ~355,000

See docs/02_TECHNICAL_SPECIFICATIONS.md Section 4.1 for full architecture.

Key dependencies:
- torch: Neural network framework
- numpy: Array operations
- scipy.sparse: For Laplacian computation (if needed)

Input data format:
- EEG: (batch, 19, 400) float32, z-scored or normalized
- True source activity: (batch, 76, 400) float32 for supervised learning

Output data format:
- Source estimate: (batch, 76, 400) float32, same scale as training targets

Author: Generated by GitHub Copilot
Date: 2026-02-18
"""

import logging
from typing import Optional, Tuple

import numpy as np
import torch
import torch.nn as nn
from numpy.typing import NDArray

# Configure module-level logger
logger = logging.getLogger(__name__)

# Module-level constants from technical specs
N_REGIONS = 76              # Desikan-Killiany atlas
N_CHANNELS = 19             # Standard 10-20 montage
WINDOW_LENGTH_SAMPLES = 400 # 2 seconds at 200 Hz


class SpatialModule(nn.Module):
    """
    Spatial module: MLPs applied independently to each time step.
    
    This module processes the spatial structure of the EEG signal by independently
    mapping each time step from 19 sensors to 76 brain regions. Weights are shared
    across all time steps, effectively applying a time-invariant spatial filter.
    
    The architecture uses skip connections to preserve gradients and allow residual
    learning of the spatial mapping. Skip connections are implemented at two levels:
    - After layer 1: concatenate and zero-pad to 256 dimensions
    - After layer 2: learned projection from 256 to 76 dimensions
    
    Architecture:
        Input (19,)
          ↓
        FC1: 19→128 + BatchNorm + ReLU
          ↓ (saved for skip)
        FC2: 128→256 + BatchNorm + ReLU
          ↓ (saved for skip)
        FC3: 256→256 + BatchNorm + ReLU + skip from FC1 (zero-padded to 256)
          ↓
        FC4: 256→128 + BatchNorm + ReLU
          ↓
        FC5: 128→76 + skip from FC2 (via learned 256→76 projection)
          ↓
        Output (76,)
    
    Total parameters in spatial module:
    - FC layers: (19→128)=2,432 + (128→256)=33,024 + (256→256)=65,792
                 + (256→128)=32,896 + (128→76)=9,804 = 143,948
    - Skip projection: (256→76)=19,532
    - BatchNorm: 4 * 256 + 128 = 1,152 (rough estimate)
    - Total: ~165,000 (includes BatchNorm parameters)
    """
    
    def __init__(self):
        """Initialize spatial module with FC layers, BatchNorm, and skip connections."""
        super().__init__()
        
        # Layer 1: 19 → 128
        self.fc1 = nn.Linear(N_CHANNELS, 128)
        self.bn1 = nn.BatchNorm1d(128)
        
        # Layer 2: 128 → 256
        self.fc2 = nn.Linear(128, 256)
        self.bn2 = nn.BatchNorm1d(256)
        
        # Layer 3: 256 → 256 with skip from layer 1 (zero-padded to 256)
        self.fc3 = nn.Linear(256, 256)
        self.bn3 = nn.BatchNorm1d(256)
        
        # Layer 4: 256 → 128
        self.fc4 = nn.Linear(256, 128)
        self.bn4 = nn.BatchNorm1d(128)
        
        # Layer 5: 128 → 76 (no BatchNorm on output)
        self.fc5 = nn.Linear(128, N_REGIONS)
        
        # Skip projection: 256 → 76 (from layer 2 output to layer 5 input)
        # This allows residual connection from midpoint of network to output
        self.skip_projection = nn.Linear(256, N_REGIONS)
        
        # Activation function
        self.relu = nn.ReLU()
    
    def forward(self, eeg: torch.Tensor) -> torch.Tensor:
        """
        Process EEG through spatial module.
        
        Args:
            eeg: Tensor of shape (batch, 19, time) or (batch, 19)
                 If 3D, process each time step independently and stack.
                 If 2D, process single time step.
        
        Returns:
            Tensor of shape (batch, 76, time) or (batch, 76)
                 Source activity estimate at each time step.
        """
        # Handle 3D input (batch, 19, time): process each time step, then stack
        if eeg.dim() == 3:
            batch_size, n_channels, n_time = eeg.shape
            # Reshape to (batch*time, 19) for processing
            eeg_flat = eeg.transpose(1, 2).reshape(-1, n_channels)  # (batch*time, 19)
            output_flat = self._forward_single(eeg_flat)             # (batch*time, 76)
            # Reshape back to (batch, time, 76) then transpose to (batch, 76, time)
            output = output_flat.reshape(batch_size, n_time, N_REGIONS).transpose(1, 2)
            return output
        else:
            # Handle 2D input (batch, 19): single time step
            return self._forward_single(eeg)
    
    def _forward_single(self, eeg: torch.Tensor) -> torch.Tensor:
        """
        Forward pass through MLP for a single time step (or batch of time steps).
        
        Args:
            eeg: Tensor of shape (batch, 19)
        
        Returns:
            Tensor of shape (batch, 76)
        """
        # Layer 1: 19→128
        x1 = self.relu(self.bn1(self.fc1(eeg)))  # (batch, 128)
        
        # Layer 2: 128→256
        x2 = self.relu(self.bn2(self.fc2(x1)))   # (batch, 256)
        
        # Layer 3: 256→256 with skip from layer 1 (zero-pad to 256)
        # Skip: concatenate x1 (128-dim) with 128 zeros to get 256-dim
        x1_padded = torch.cat([x1, torch.zeros_like(x1)], dim=1)  # (batch, 256)
        x3 = self.relu(self.bn3(self.fc3(x2) + x1_padded))       # (batch, 256)
        
        # Layer 4: 256→128
        x4 = self.relu(self.bn4(self.fc4(x3)))   # (batch, 128)
        
        # Layer 5: 128→76 with skip from layer 2 (via learned projection)
        # Skip: project x2 (256-dim) to 76-dim
        x2_proj = self.skip_projection(x2)       # (batch, 76)
        output = self.fc5(x4) + x2_proj          # (batch, 76)
        
        return output


class TemporalModule(nn.Module):
    """
    Temporal module: BiLSTM layers with output projection and skip connection.
    
    This module enforces temporal consistency in the source estimates by processing
    the entire time series through bidirectional LSTM layers. Bidirectional LSTMs
    allow each time step to incorporate context from both past and future, which is
    appropriate for offline analysis. The module includes a skip connection from the
    spatial module output to preserve spatial information.
    
    Architecture:
        Input from Spatial Module: (batch, 76, time)
          ↓
        Transpose to sequence format: (batch, time, 76)
          ↓
        BiLSTM Layer 1: 76 → (2×76=152) [bidirectional]
          ↓
        BiLSTM Layer 2: 152 → (2×76=152) [bidirectional]
          ↓
        Output projection: 152 → 76
          ↓
        Skip connection: add spatial module output element-wise
          ↓
        Output: (batch, 76, time)
    
    Total parameters in temporal module:
    - BiLSTM 1: input_size=76, hidden_size=76, num_layers=1, bidirectional=True
      Parameters per direction: 4 * (76 + 76) * 76 = 46,336 (4 gates)
      Total: 2 * 46,336 = 92,672
    - BiLSTM 2: input_size=152, hidden_size=76, bidirectional=True
      Parameters per direction: 4 * (152 + 76) * 76 = 69,632
      Total: 2 * 69,632 = 139,264
    - Output projection: (152+0)×76 = 11,552
    - Total: ~243,000
    
    Note: Actual parameter count may be slightly higher due to bias terms and
    implementation details in PyTorch's LSTM.
    """
    
    def __init__(self, dropout: float = 0.1):
        """
        Initialize temporal module with BiLSTM layers.
        
        Args:
            dropout: Dropout probability for LSTM layers. Default 0.1
                     Helps regularize during training, disabled during inference.
        """
        super().__init__()
        
        # BiLSTM Layer 1: 76 → 76 (bidirectional outputs 152-dim)
        # Takes spatial module output (76-dim per time step)
        # Each direction produces 76-dim, result is 152-dim when concatenated
        self.lstm1 = nn.LSTM(
            input_size=N_REGIONS,
            hidden_size=N_REGIONS,
            num_layers=1,
            bidirectional=True,
            dropout=dropout if dropout > 0 else 0,
            batch_first=True,  # Input is (batch, time, features)
        )
        
        # BiLSTM Layer 2: 152 → 76 (bidirectional outputs 152-dim)
        # Takes concatenated output from first LSTM (152-dim per time step)
        self.lstm2 = nn.LSTM(
            input_size=2 * N_REGIONS,  # 152 (concatenated from bidirectional)
            hidden_size=N_REGIONS,
            num_layers=1,
            bidirectional=True,
            dropout=dropout if dropout > 0 else 0,
            batch_first=True,
        )
        
        # Output projection: 152 → 76
        # Converts bidirectional LSTM output back to region dimension
        self.output_projection = nn.Linear(2 * N_REGIONS, N_REGIONS)
    
    def forward(
        self,
        spatial_output: torch.Tensor,
    ) -> torch.Tensor:
        """
        Process spatial module output through temporal module.
        
        Args:
            spatial_output: Tensor of shape (batch, 76, time)
                           Output from spatial module, one row per region
        
        Returns:
            Tensor of shape (batch, 76, time)
                   Temporally-smoothed source estimate, combined with spatial
                   module output via skip connection
        """
        batch_size, n_regions, n_time = spatial_output.shape
        
        # Transpose to sequence format for LSTM: (batch, time, 76)
        x = spatial_output.transpose(1, 2)
        
        # BiLSTM Layer 1: (batch, time, 76) → (batch, time, 152)
        # Returns (output, (h_n, c_n)) where output has shape (batch, time, 2*hidden)
        lstm1_output, (h1, c1) = self.lstm1(x)
        
        # BiLSTM Layer 2: (batch, time, 152) → (batch, time, 152)
        lstm2_output, (h2, c2) = self.lstm2(lstm1_output)
        
        # Output projection: (batch, time, 152) → (batch, time, 76)
        temporal_output = self.output_projection(lstm2_output)
        
        # Transpose back to (batch, 76, time)
        temporal_output = temporal_output.transpose(1, 2)
        
        # Skip connection: add spatial module output element-wise
        # This residual connection preserves spatial information and helps
        # gradient flow during backpropagation
        output = temporal_output + spatial_output
        
        return output


class PhysDeepSIF(nn.Module):
    """
    PhysDeepSIF: Physics-informed deep learning EEG inverse solver.
    
    This is the main network that combines spatial and temporal modules to
    map 19-channel EEG to 76-region source activity estimates. It also
    registers physics priors (leadfield, connectivity Laplacian) as
    non-trainable buffers for use in the loss function.
    
    Architecture:
        Input EEG: (batch, 19, 400)
          ↓
        Spatial Module: (batch, 19, 400) → (batch, 76, 400)
          ↓
        Temporal Module: (batch, 76, 400) → (batch, 76, 400)
          ↓
        Output: Source estimate (batch, 76, 400)
    
    Physics buffers (non-learnable):
        - leadfield: (19, 76) — maps source activity to EEG via matrix product
        - connectivity_laplacian: (76, 76) — encodes structural connectivity
    
    Total learnable parameters: ~355,000
    Total buffers (non-learnable): 19*76 + 76*76 = 7,300
    
    The network is designed to work with a composite physics-informed loss
    function that includes:
    1. Source reconstruction loss (supervised)
    2. Forward consistency loss (using leadfield buffer)
    3. Physiological regularization (using Laplacian buffer)
    """
    
    def __init__(
        self,
        leadfield: NDArray[np.float32],
        connectivity_laplacian: NDArray[np.float32],
        lstm_dropout: float = 0.1,
    ):
        """
        Initialize PhysDeepSIF network.
        
        Args:
            leadfield: Leadfield matrix (19, 76) mapping regions to channels.
                      Will be registered as non-trainable buffer (frozen weights).
                      Shape must be (19, 76), dtype float32.
            
            connectivity_laplacian: Graph Laplacian of connectivity matrix (76, 76).
                                   Computed as L = diag(W·1) - W where W is the
                                   symmetric connectivity matrix. Will be registered
                                   as non-trainable buffer.
                                   Shape must be (76, 76), dtype float32.
            
            lstm_dropout: Dropout probability for LSTM layers (default 0.1).
                         Helps regularize the temporal module. Set to 0 for no dropout.
        
        Raises:
            ValueError: If leadfield or connectivity_laplacian have incorrect shapes.
        """
        super().__init__()
        
        # Validate input shapes
        if leadfield.shape != (N_CHANNELS, N_REGIONS):
            raise ValueError(
                f"Leadfield shape must be ({N_CHANNELS}, {N_REGIONS}), "
                f"got {leadfield.shape}"
            )
        if connectivity_laplacian.shape != (N_REGIONS, N_REGIONS):
            raise ValueError(
                f"Connectivity Laplacian shape must be ({N_REGIONS}, {N_REGIONS}), "
                f"got {connectivity_laplacian.shape}"
            )
        
        # Convert numpy arrays to PyTorch tensors (float32)
        leadfield_tensor = torch.from_numpy(leadfield).float()
        laplacian_tensor = torch.from_numpy(connectivity_laplacian).float()
        
        # Register as non-trainable buffers
        # These will be moved to correct device automatically with model.to(device)
        # and saved/loaded with model.state_dict()
        self.register_buffer('leadfield', leadfield_tensor)
        self.register_buffer('connectivity_laplacian', laplacian_tensor)
        
        # Instantiate spatial and temporal modules
        self.spatial_module = SpatialModule()
        self.temporal_module = TemporalModule(dropout=lstm_dropout)
        
        logger.info(
            f"PhysDeepSIF initialized with leadfield {leadfield.shape}, "
            f"laplacian {connectivity_laplacian.shape}, lstm_dropout={lstm_dropout}"
        )
    
    def forward(self, eeg: torch.Tensor) -> torch.Tensor:
        """
        Forward pass through PhysDeepSIF network.
        
        Args:
            eeg: Input EEG tensor of shape (batch, 19, 400)
                 - batch: number of samples in batch (typically 1-64)
                 - 19: number of EEG channels (standard 10-20 montage)
                 - 400: number of time points (2 seconds at 200 Hz)
                 Typically z-scored or normalized before input.
        
        Returns:
            source_estimate: Output tensor of shape (batch, 76, 400)
                            Predicted source activity for each brain region and time point
                            Same scale/units as training targets (usually normalized)
        
        Example:
            >>> model = PhysDeepSIF(leadfield, laplacian)
            >>> eeg = torch.randn(32, 19, 400)  # Batch of 32 samples
            >>> source_est = model(eeg)
            >>> source_est.shape
            torch.Size([32, 76, 400])
        """
        # Spatial module: (batch, 19, 400) → (batch, 76, 400)
        spatial_out = self.spatial_module(eeg)
        
        # Temporal module: (batch, 76, 400) → (batch, 76, 400)
        source_estimate = self.temporal_module(spatial_out)
        
        return source_estimate
    
    def get_parameter_count(self) -> dict:
        """
        Get breakdown of trainable and non-trainable parameters.
        
        Returns:
            dict with keys:
            - 'spatial': number of trainable parameters in spatial module
            - 'temporal': number of trainable parameters in temporal module
            - 'total_trainable': total trainable parameters
            - 'total_buffers': total non-trainable buffer parameters
            - 'total': sum of trainable and non-trainable
        """
        spatial_params = sum(p.numel() for p in self.spatial_module.parameters())
        temporal_params = sum(p.numel() for p in self.temporal_module.parameters())
        
        buffer_params = sum(b.numel() for b in self.buffers())
        
        return {
            'spatial': spatial_params,
            'temporal': temporal_params,
            'total_trainable': spatial_params + temporal_params,
            'total_buffers': buffer_params,
            'total': spatial_params + temporal_params + buffer_params,
        }


def build_physdeepsif(
    leadfield_path: str,
    connectivity_path: str,
    lstm_dropout: float = 0.1,
) -> PhysDeepSIF:
    """
    Convenience function to build PhysDeepSIF network from file paths.
    
    Loads leadfield and connectivity matrices from disk, computes the
    connectivity Laplacian, and instantiates the network.
    
    Args:
        leadfield_path: Path to leadfield.npy (shape 19×76)
        connectivity_path: Path to connectivity.npy (shape 76×76, symmetric)
        lstm_dropout: Dropout probability for LSTM layers
    
    Returns:
        PhysDeepSIF: Initialized network ready for training/inference
    
    Raises:
        FileNotFoundError: If files do not exist
        ValueError: If data shapes are incorrect
    """
    # Load matrices
    leadfield = np.load(leadfield_path).astype(np.float32)
    connectivity = np.load(connectivity_path).astype(np.float32)
    
    logger.info(f"Loaded leadfield from {leadfield_path} (shape {leadfield.shape})")
    logger.info(f"Loaded connectivity from {connectivity_path} (shape {connectivity.shape})")
    
    # Compute Laplacian: L = diag(W·1) - W
    # W·1 gives the row sums (degree of each node)
    connectivity_degree_vector = connectivity.sum(axis=1)  # (76,)
    connectivity_laplacian = np.diag(connectivity_degree_vector) - connectivity  # (76, 76)
    
    logger.info(f"Computed connectivity Laplacian (shape {connectivity_laplacian.shape})")
    
    # Build network
    model = PhysDeepSIF(
        leadfield=leadfield,
        connectivity_laplacian=connectivity_laplacian,
        lstm_dropout=lstm_dropout,
    )
    
    # Log parameter count
    param_counts = model.get_parameter_count()
    logger.info(f"Built PhysDeepSIF network:")
    logger.info(f"  Spatial module: {param_counts['spatial']:,} parameters")
    logger.info(f"  Temporal module: {param_counts['temporal']:,} parameters")
    logger.info(f"  Total trainable: {param_counts['total_trainable']:,} parameters")
    logger.info(f"  Total parameters (including buffers): {param_counts['total']:,}")
    
    return model
