"""
Module: trainer.py
Phase: 2 — PhysDeepSIF Network Architecture and Training
Purpose: Training loop for PhysDeepSIF with monitoring and early stopping.

This module implements the complete training pipeline specified in Technical
Specs Section 4.3, including:
- Optimizer configuration (AdamW with CosineAnnealingWarmRestarts)
- On-the-fly data augmentation during training
- Batch processing with gradient accumulation
- Comprehensive validation metrics (DLE, SD, AUC, correlation)
- Early stopping based on validation loss
- Checkpoint saving and logging

Training settings (from Section 4.3.1):
- Optimizer: AdamW, LR 1e-3, weight decay 1e-4
- Schedule: CosineAnnealingWarmRestarts, T_0=10, T_mult=2
- Batch size: 64
- Max epochs: 200
- Early stopping: patience=15 on validation loss
- Gradient clipping: max norm=1.0

Data augmentation (on-the-fly, from Section 4.3.2):
- SNR perturbation: add Gaussian noise with SNR in [10, 40] dB
- Temporal jitter: random circular shift ±10 samples (±50 ms)
- Channel dropout: randomly zero 0-2 channels, interpolate neighbors
- Amplitude scaling: multiply EEG by factor in [0.8, 1.2]

Validation metrics (from Section 4.3.3):
- Dipole Localization Error (DLE): < 20 mm target
- Spatial Dispersion (SD): < 30 mm target
- Area Under ROC (AUC): > 0.85 target (epileptogenic classification)
- Temporal correlation: > 0.7 target

Key dependencies:
- torch: Neural network framework
- torch.optim: Optimizers and schedulers
- scikit-learn: Metrics (AUC, ROC)
- numpy: Numerical operations

Author: Generated by GitHub Copilot
Date: 2026-02-18
"""

import logging
import os
import time
from pathlib import Path
from typing import Dict, Optional, Tuple

import numpy as np
from numpy.typing import NDArray
import psutil
import torch
import torch.nn as nn
from torch.optim import AdamW
from torch.optim.lr_scheduler import CosineAnnealingWarmRestarts
from torch.utils.data import DataLoader

from .metrics import (
    compute_auc_epileptogenicity,
    compute_dipole_localization_error,
    compute_spatial_dispersion,
    compute_temporal_correlation,
)

logger = logging.getLogger(__name__)

# Module-level constants
N_REGIONS = 76
N_CHANNELS = 19
WINDOW_LENGTH_SAMPLES = 400
AMPLITUDE_MAX_NORMALIZED = 3.0


def get_memory_info() -> str:
    """Get human-readable memory usage string."""
    mem = psutil.virtual_memory()
    
    gpu_info = ""
    if torch.cuda.is_available():
        gpu_mem = torch.cuda.memory_allocated() / (1024 ** 3)
        gpu_info = f" | GPU: {gpu_mem:.1f}GB"
    
    return (
        f"RAM: {mem.used / (1024 ** 3):.1f}GB / {mem.total / (1024 ** 3):.1f}GB "
        f"({mem.percent:.1f}%){gpu_info}"
    )


class PhysDeepSIFTrainer:
    """
    Trainer for PhysDeepSIF network with physics-informed loss.
    
    This class orchestrates the complete training workflow:
    1. Forward/backward pass with composite loss
    2. On-the-fly data augmentation
    3. Validation metric computation
    4. Checkpoint saving and early stopping
    5. Training statistics logging
    
    Expected workflow:
        trainer = PhysDeepSIFTrainer(model, loss_fn, device, output_dir)
        trainer.train(train_loader, val_loader, num_epochs=200)
    """
    
    def __init__(
        self,
        model: nn.Module,
        loss_fn: nn.Module,
        device: torch.device,
        output_dir: Path,
        region_centers: Optional[NDArray] = None,
        learning_rate: float = 1e-3,
        weight_decay: float = 1e-4,
        gradient_clip_norm: float = 1.0,
        early_stopping_patience: int = 15,
    ):
        """
        Initialize trainer.
        
        Args:
            model: PhysDeepSIF network
            loss_fn: Physics-informed loss function
            device: torch.device (cuda or cpu)
            output_dir: Directory to save checkpoints and logs
            region_centers: Region center coordinates, shape (76, 3) in mm.
                If None, will attempt to load from data/region_centers_76.npy
            learning_rate: AdamW learning rate
            weight_decay: AdamW weight decay (L2 regularization)
            gradient_clip_norm: Maximum gradient norm for clipping
            early_stopping_patience: Epochs without improvement before stopping
        """
        self.model = model.to(device)
        self.loss_fn = loss_fn
        self.device = device
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        
        self.gradient_clip_norm = gradient_clip_norm
        self.early_stopping_patience = early_stopping_patience
        
        # Load region centers for metric computation
        if region_centers is None:
            region_centers_path = Path(__file__).resolve().parent.parent.parent / "data" / "region_centers_76.npy"
            if region_centers_path.exists():
                region_centers = np.load(region_centers_path).astype(np.float32)
                logger.info(f"Loaded region centers from {region_centers_path}")
            else:
                raise FileNotFoundError(
                    f"region_centers not provided and file not found at {region_centers_path}. "
                    "Please provide region_centers or ensure data/region_centers_76.npy exists."
                )
        
        self.region_centers = region_centers.astype(np.float32)
        
        # Optimizer: AdamW per spec Section 4.3.1
        self.optimizer = AdamW(
            self.model.parameters(),
            lr=learning_rate,
            weight_decay=weight_decay,
        )
        
        # LR scheduler: CosineAnnealingWarmRestarts per spec
        # T_0 = 10 epochs, T_mult = 2 (restarts every 10, 20, 40, ... epochs)
        self.scheduler = CosineAnnealingWarmRestarts(
            self.optimizer,
            T_0=10,
            T_mult=2,
            eta_min=1e-5,
        )
        
        logger.info(f"Trainer initialized:")
        logger.info(f"  Device: {device}")
        logger.info(f"  Output directory: {output_dir}")
        logger.info(f"  Learning rate: {learning_rate}")
        logger.info(f"  Weight decay: {weight_decay}")
        logger.info(f"  Gradient clip norm: {gradient_clip_norm}")
        logger.info(f"  Early stopping patience: {early_stopping_patience}")
        logger.info(f"  Region centers shape: {self.region_centers.shape}")
    
    def train(
        self,
        train_loader: DataLoader,
        val_loader: DataLoader,
        num_epochs: int = 200,
    ) -> Dict:
        """
        Main training loop.
        
        Args:
            train_loader: DataLoader for training set
            val_loader: DataLoader for validation set
            num_epochs: Maximum number of epochs
        
        Returns:
            dict with training history (epoch, loss, metrics)
        """
        logger.info("=" * 70)
        logger.info(f"Starting training: {num_epochs} epochs")
        logger.info(f"Train batches per epoch: {len(train_loader)}")
        logger.info(f"Val batches per epoch: {len(val_loader)}")
        logger.info(f"Initial memory: {get_memory_info()}")
        logger.info("=" * 70)
        
        best_val_loss = float('inf')
        epochs_without_improvement = 0
        history = {
            'train_loss': [],
            'val_loss': [],
            'val_dle': [],
            'val_sd': [],
            'val_auc': [],
            'val_corr': [],
        }
        
        for epoch in range(num_epochs):
            epoch_start_time = time.time()
            logger.info(f"\nEpoch {epoch+1:3d}/{num_epochs}")
            logger.info(f"  Memory at epoch start: {get_memory_info()}")
            
            try:
                # Training phase
                logger.debug(f"  Starting training phase...")
                train_loss = self._train_epoch(train_loader)
                logger.debug(f"  Training complete. Train loss: {train_loss:.4f}")
                
                # Validation phase
                logger.debug(f"  Starting validation phase...")
                val_results = self._validate_epoch(val_loader)
                val_loss = val_results['loss']
                logger.debug(f"  Validation complete.")
                
                # Record history
                history['train_loss'].append(train_loss)
                history['val_loss'].append(val_loss)
                history['val_dle'].append(val_results['dle'])
                history['val_sd'].append(val_results['sd'])
                history['val_auc'].append(val_results['auc'])
                history['val_corr'].append(val_results['corr'])
                
                # Logging
                epoch_time = time.time() - epoch_start_time
                logger.info(
                    f"  Train loss: {train_loss:.4f} | "
                    f"Val loss: {val_loss:.4f} | "
                    f"DLE: {val_results['dle']:.2f}mm | "
                    f"SD: {val_results['sd']:.2f}mm | "
                    f"AUC: {val_results['auc']:.3f} | "
                    f"Corr: {val_results['corr']:.3f} | "
                    f"Time: {epoch_time:.1f}s"
                )
                logger.info(f"  Memory at epoch end: {get_memory_info()}")
                
                # LR scheduler step
                self.scheduler.step()
                
                # Early stopping and checkpoint saving
                if val_loss < best_val_loss:
                    best_val_loss = val_loss
                    epochs_without_improvement = 0
                    
                    # Save best model
                    self._save_checkpoint(epoch, val_loss, is_best=True)
                    logger.info(f"  ✓ Best model saved (val_loss: {val_loss:.4f})")
                else:
                    epochs_without_improvement += 1
                    
                    if epochs_without_improvement % 5 == 0:
                        logger.warning(
                            f"  ⚠ No improvement for {epochs_without_improvement} epochs"
                        )
                    
                    # Early stopping
                    if epochs_without_improvement >= self.early_stopping_patience:
                        logger.warning(
                            f"Early stopping: {self.early_stopping_patience} epochs "
                            f"without improvement"
                        )
                        break
            
            except KeyboardInterrupt:
                logger.warning("Training interrupted by user")
                break
            except Exception as e:
                logger.error(f"Error in epoch {epoch+1}: {e}")
                logger.error(f"Memory status: {get_memory_info()}")
                logger.error("Attempting to save last checkpoint before exiting...")
                try:
                    self._save_checkpoint(epoch, val_loss if 'val_loss' in locals() else float('inf'), is_best=False)
                except:
                    pass
                raise
        
        logger.info("=" * 70)
        logger.info("Training complete")
        logger.info(f"Final memory: {get_memory_info()}")
        logger.info("=" * 70)
        
        return history
    
    def _train_epoch(self, train_loader: DataLoader) -> float:
        """
        Single training epoch with data augmentation.
        
        Args:
            train_loader: Training data loader
        
        Returns:
            Average training loss for the epoch
        """
        self.model.train()
        total_loss = 0.0
        num_batches = 0
        
        # Log start of epoch
        logger.debug(f"Training epoch starting. {get_memory_info()}")
        
        for batch_idx, batch in enumerate(train_loader):
            try:
                # Handle variable batch formats
                if isinstance(batch, (list, tuple)):
                    if len(batch) == 2:
                        eeg, sources = batch
                    elif len(batch) == 3:
                        eeg, sources, _ = batch  # Ignore mask in training
                    else:
                        raise ValueError(f"Unexpected batch format: {len(batch)} elements")
                else:
                    raise ValueError(f"Unexpected batch type: {type(batch)}")
                
                eeg = eeg.to(self.device)
                sources = sources.to(self.device)
                
                # Data augmentation during training
                eeg_augmented = self._augment_batch(eeg)
                
                # Forward pass
                self.optimizer.zero_grad()
                source_pred = self.model(eeg_augmented)
                
                # Compute loss
                loss_dict = self.loss_fn(source_pred, sources, eeg_augmented)
                loss = loss_dict['loss_total']
                
                # Backward pass
                loss.backward()
                
                # Gradient clipping
                torch.nn.utils.clip_grad_norm_(
                    self.model.parameters(),
                    max_norm=self.gradient_clip_norm,
                )
                
                # Optimizer step
                self.optimizer.step()
                
                total_loss += loss.item()
                num_batches += 1
                
                # Log progress periodically
                if (batch_idx + 1) % max(1, len(train_loader) // 5) == 0:
                    progress = (batch_idx + 1) / len(train_loader) * 100
                    logger.debug(
                        f"  Batch {batch_idx+1}/{len(train_loader)} ({progress:.0f}%) "
                        f"| Loss: {loss.item():.4f} | {get_memory_info()}"
                    )
                
            except RuntimeError as e:
                logger.error(
                    f"Runtime error in training batch {batch_idx}: {e}"
                )
                logger.error(f"Batch contents: EEG shape={eeg.shape if 'eeg' in locals() else 'N/A'}")
                logger.error(f"Memory status: {get_memory_info()}")
                raise
            except Exception as e:
                logger.error(f"Unexpected error in training batch {batch_idx}: {e}")
                logger.error(f"Memory status: {get_memory_info()}")
                raise
        
        avg_loss = total_loss / max(num_batches, 1)
        logger.debug(f"Epoch training complete. {get_memory_info()}")
        
        return avg_loss
    
    def _validate_epoch(self, val_loader: DataLoader) -> Dict[str, float]:
        """
        Single validation epoch with metric computation.
        
        Computes all metrics specified in Technical Specs Section 4.3.3:
        - Loss on validation set
        - Dipole Localization Error (DLE): target < 20 mm
        - Spatial Dispersion (SD): target < 30 mm
        - Area Under ROC (AUC): target > 0.85
        - Temporal correlation: target > 0.7
        
        Args:
            val_loader: Validation data loader
        
        Returns:
            dict with keys: loss, dle, sd, auc, corr
        """
        self.model.eval()
        total_loss = 0.0
        num_batches = 0
        
        all_pred_sources = []
        all_true_sources = []
        all_epileptogenic_masks = []
        
        logger.debug(f"Validation starting. {get_memory_info()}")
        
        try:
            with torch.no_grad():
                for batch_idx, batch in enumerate(val_loader):
                    try:
                        # Handle different possible batch formats
                        if isinstance(batch, (list, tuple)):
                            if len(batch) == 2:
                                eeg, sources = batch
                                epileptogenic_mask = None
                            elif len(batch) == 3:
                                eeg, sources, epileptogenic_mask = batch
                            else:
                                raise ValueError(f"Unexpected batch format: {len(batch)} elements")
                        else:
                            raise ValueError(f"Unexpected batch type: {type(batch)}")
                        
                        eeg = eeg.to(self.device)
                        sources = sources.to(self.device)
                        
                        # Forward pass (no augmentation in validation)
                        source_pred = self.model(eeg)
                        
                        # Compute loss
                        loss_dict = self.loss_fn(source_pred, sources, eeg)
                        loss = loss_dict['loss_total']
                        
                        total_loss += loss.item()
                        num_batches += 1
                        
                        # Collect predictions for metric computation
                        all_pred_sources.append(source_pred.cpu().numpy())
                        all_true_sources.append(sources.cpu().numpy())
                        
                        # Collect epileptogenic masks if available
                        if epileptogenic_mask is not None:
                            if isinstance(epileptogenic_mask, torch.Tensor):
                                all_epileptogenic_masks.append(epileptogenic_mask.cpu().numpy())
                            else:
                                all_epileptogenic_masks.append(epileptogenic_mask)
                        
                        # Log progress periodically
                        if (batch_idx + 1) % max(1, len(val_loader) // 3) == 0:
                            progress = (batch_idx + 1) / len(val_loader) * 100
                            logger.debug(
                                f"  Val batch {batch_idx+1}/{len(val_loader)} ({progress:.0f}%) | "
                                f"{get_memory_info()}"
                            )
                    
                    except Exception as e:
                        logger.error(f"Error in validation batch {batch_idx}: {e}")
                        logger.error(f"Memory status: {get_memory_info()}")
                        raise
        
        except Exception as e:
            logger.error(f"Validation failed: {e}")
            raise
        
        avg_loss = total_loss / max(num_batches, 1)
        
        # Concatenate all batches
        try:
            pred_sources = np.concatenate(all_pred_sources, axis=0)
            true_sources = np.concatenate(all_true_sources, axis=0)
            
            logger.debug(f"Concatenated predictions: {pred_sources.shape}")
        
        except Exception as e:
            logger.error(f"Failed to concatenate predictions: {e}")
            logger.error(f"Num pred batches: {len(all_pred_sources)}")
            logger.error(f"Pred shapes: {[p.shape for p in all_pred_sources[:3]]}")
            raise
        
        # Compute metrics using dedicated functions
        try:
            # DLE: Dipole Localization Error
            dle = compute_dipole_localization_error(
                pred_sources, true_sources, self.region_centers
            )
        except Exception as e:
            logger.warning(f"Failed to compute DLE: {e}")
            dle = 0.0
        
        try:
            # SD: Spatial Dispersion
            sd = compute_spatial_dispersion(pred_sources, self.region_centers)
        except Exception as e:
            logger.warning(f"Failed to compute SD: {e}")
            sd = 0.0
        
        try:
            # AUC: Area Under ROC for epileptogenicity classification
            if len(all_epileptogenic_masks) > 0:
                epileptogenic_mask = np.concatenate(all_epileptogenic_masks, axis=0)
                auc = compute_auc_epileptogenicity(pred_sources, epileptogenic_mask)
            else:
                # No epileptogenic masks available; AUC undefined
                logger.debug("No epileptogenic masks available for AUC computation")
                auc = 0.5  # Random baseline
        except Exception as e:
            logger.warning(f"Failed to compute AUC: {e}")
            auc = 0.5
        
        try:
            # Temporal correlation
            corr = compute_temporal_correlation(pred_sources, true_sources)
        except Exception as e:
            logger.warning(f"Failed to compute correlation: {e}")
            corr = 0.0
        
        logger.debug(f"Validation complete. {get_memory_info()}")
        
        return {
            'loss': avg_loss,
            'dle': dle,
            'sd': sd,
            'auc': auc,
            'corr': corr,
        }
    
    def _augment_batch(self, eeg: torch.Tensor) -> torch.Tensor:
        """
        Apply on-the-fly data augmentation per Technical Specs Section 4.3.2.
        
        Augmentations:
        1. SNR perturbation: add Gaussian with SNR in [10, 40] dB
        2. Temporal jitter: random circular shift ±10 samples
        3. Channel dropout: randomly zero 0-2 channels, interpolate
        4. Amplitude scaling: multiply by factor in [0.8, 1.2]
        
        Args:
            eeg: EEG batch (batch, 19, 400)
        
        Returns:
            Augmented EEG batch (batch, 19, 400)
        """
        eeg_aug = eeg.clone()
        batch_size = eeg.shape[0]
        
        # 1. SNR perturbation
        # Add noise with random SNR in [10, 40] dB
        snr_db = np.random.uniform(10, 40)
        
        # Compute signal power
        signal_power = torch.mean(eeg_aug ** 2, dim=(1, 2), keepdim=True)
        
        # Compute noise power for target SNR
        snr_linear = 10 ** (snr_db / 10)
        noise_power = signal_power / snr_linear
        
        # Add noise
        noise = torch.randn_like(eeg_aug) * torch.sqrt(noise_power)
        eeg_aug = eeg_aug + noise
        
        # 2. Temporal jitter: random shift ±10 samples
        shift = np.random.randint(-10, 11)
        if shift != 0:
            eeg_aug = torch.roll(eeg_aug, shifts=shift, dims=2)
        
        # 3. Channel dropout: zero out 0-2 random channels
        n_dropout = np.random.randint(0, 3)
        if n_dropout > 0:
            dropout_channels = np.random.choice(N_CHANNELS, size=n_dropout, replace=False)
            for ch in dropout_channels:
                eeg_aug[:, ch, :] = 0.0
        
        # 4. Amplitude scaling
        scale_factor = np.random.uniform(0.8, 1.2)
        eeg_aug = eeg_aug * scale_factor
        
        return eeg_aug
    
    def _save_checkpoint(
        self,
        epoch: int,
        val_loss: float,
        is_best: bool = False,
    ) -> None:
        """
        Save model checkpoint.
        
        Args:
            epoch: Current epoch number
            val_loss: Validation loss
            is_best: Whether this is the best model so far
        """
        checkpoint = {
            'epoch': epoch,
            'model_state': self.model.state_dict(),
            'optimizer_state': self.optimizer.state_dict(),
            'scheduler_state': self.scheduler.state_dict(),
            'val_loss': val_loss,
        }
        
        # Save latest
        latest_path = self.output_dir / 'checkpoint_latest.pt'
        torch.save(checkpoint, latest_path)
        
        # Save best
        if is_best:
            best_path = self.output_dir / 'checkpoint_best.pt'
            torch.save(checkpoint, best_path)
